pipeline {
  agent {
   	kubernetes {
      yamlFile 'ci/pod.yaml'
  	}
  }
	triggers {
		pollSCM('H/5 * * * *')
	}
  stages {
    stage('clone') {
      steps {
        container('buildkit') {
					checkout scmGit(userRemoteConfigs: [
                    [ url: 'https://github.com/caffeinatedope/blog' ]
                ])
        }
      }
    }
		stage('install dependencies') {
			steps {
				container ('node') {
					sh 'cd /home/jenkins/agent/workspace/blog/ && npm install'
				}
			}
		}
		stage('build') {
			steps {
				container('node') {
					dir {
						path: '/home/jenkins/agent/workspace/blog/'
						sh 'npm build'
					}
				}
			}
		}
    stage('build and push') {
      steps {
        container('buildkit') {
          sh 'cd blog && buildctl-daemonless.sh build . --output type=image,name=ghcr.io/caffeinatedope/blog,push=true,tag=$(date +%s) --frontend dockerfile.v0 --local context=. --local dockerfile=ci/.'
        }
      }
    }
  }
}
