pipeline {
  agent {
      kubernetes {
        yamlFile 'ci/pod.yaml'
      }
  }
  stages {
    stage('clone') {
    	steps {
      	container('buildkit') {
        	git branch: 'master', changelog: false, poll: false, url: 'https://github.com/CaffeinatedOpe/blog'
      	}
    	}
    }
    stage('build and push') {
    	steps {
      	container('buildkit') {
        	sh 'buildctl-daemonless.sh build . --output type=image,name=ghcr.io/CaffeinatedOpe/blog,push=true --frontend dockerfile.v0 --local context=. --local dockerfile=.'
      	}
    	}
    }
	}
}
