apiVersion: v1
kind: Pod
spec:
  containers:
  - name: buildkit
    image: docker.io/moby/buildkit:latest
    command: ["/bin/sh", "/code/build.sh"]
    securityContext:
			privileged: true
		envFrom:
		- configMapRef:
		    name: build-config
		volumeMounts:
	  - name: registry-creds
	    mountPath: /root/.docker
	    readOnly: true
  volumes:
    - name: registry-creds
      secret:
        secretName: registry-creds
        defaultMode: 0400
        items:
          - key: .dockerconfigjson
            path: config.json