apiVersion: v1
kind: Pod
metadata:
  name: buildkit
spec:
  containers:
    - name: buildkit
      image: moby/buildkit:latest
      envFrom:
        - configMapRef:
          name: build-config
      volumeMounts:
        - name: registry-creds
          mountPath: /root/.docker
          readOnly: true
  volumes:
    - name: registry-creds
      secret:
        secretName: registry-creds
        defaultMode: 0400
        items:
          - key: .dockerconfigjson
            path: config.json