apiVersion: v1
kind: Pod
metadata:
  name: buildkit
spec:
  containers:
    - name: buildkit
      image: moby/buildkit:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: registry-creds
          mountPath: /root/.docker
          readOnly: true
        - name: workspace
          mountPath: /blog
          readOnly: false
  volumes:
    - name: registry-creds
      secret:
        secretName: registry-creds
        defaultMode: 0400
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: workspace
      emptyDir: {}
